CREATE TABLE IF NOT EXISTS `membership_payment_order` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `order_no` VARCHAR(64) NOT NULL COMMENT '平台会员订单号，PM 前缀',
    `user_id` BIGINT NOT NULL COMMENT '购买用户 ID',
    `idempotency_key` VARCHAR(64) NOT NULL COMMENT '客户端幂等键',
    `active_order_key` VARCHAR(96) NULL COMMENT '用户当前未终结会员订单唯一键',
    `coupon_code_id` BIGINT NULL COMMENT '支付优惠码 ID',
    `coupon_code_snapshot` VARCHAR(64) NULL COMMENT '优惠码快照',
    `membership_days` INT NOT NULL COMMENT '本订单购买的会员天数快照',
    `list_price_cents` INT NOT NULL COMMENT '会员原价快照，单位分',
    `discount_amount_cents` INT NOT NULL DEFAULT 0 COMMENT '优惠金额快照，单位分',
    `payable_amount_cents` INT NOT NULL COMMENT '应付金额快照，单位分',
    `currency` VARCHAR(8) NOT NULL DEFAULT 'CNY' COMMENT '币种',
    `provider` VARCHAR(24) NOT NULL COMMENT '支付提供方',
    `pay_channel` VARCHAR(24) NOT NULL COMMENT '支付渠道',
    `order_status` VARCHAR(24) NOT NULL DEFAULT 'CREATED' COMMENT 'CREATED/PREPAYING/PREPAY_UNKNOWN/PENDING/EXPIRED/CANCELED/PAID/REFUND_REQUIRED',
    `provider_prepay_id` VARCHAR(128) NULL COMMENT '支付平台预支付标识',
    `code_url` TEXT NULL COMMENT 'Native 支付二维码内容',
    `provider_transaction_id` VARCHAR(128) NULL COMMENT '支付平台交易号',
    `expires_at` DATETIME NOT NULL COMMENT '支付截止时间',
    `last_checked_at` DATETIME NULL COMMENT '最近一次主动查单时间',
    `paid_at` DATETIME NULL COMMENT '支付完成时间',
    `closed_at` DATETIME NULL COMMENT '支付平台确认关单时间',
    `membership_started_at` DATETIME NULL COMMENT '本订单权益起始时间',
    `membership_expires_at` DATETIME NULL COMMENT '本订单结算后的会员到期时间',
    `payment_review_reason` VARCHAR(255) NULL COMMENT '人工复核原因',
    `reconcile_lease_token` VARCHAR(64) NULL COMMENT '跨节点对账租约 token',
    `reconcile_lease_until` DATETIME NULL COMMENT '跨节点对账租约到期时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_membership_order_no` (`order_no`),
    UNIQUE KEY `uk_membership_order_idempotency` (`user_id`, `idempotency_key`),
    UNIQUE KEY `uk_membership_order_active` (`active_order_key`),
    UNIQUE KEY `uk_membership_order_transaction` (`provider`, `provider_transaction_id`),
    KEY `idx_membership_order_user` (`user_id`, `created_at`),
    KEY `idx_membership_order_reconcile` (`provider`, `order_status`, `expires_at`, `last_checked_at`),
    CONSTRAINT `fk_membership_order_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会员在线支付订单';
