CREATE TABLE IF NOT EXISTS `resume_market_listing` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `resume_id` BIGINT NOT NULL COMMENT '发布源简历 ID',
    `seller_user_id` BIGINT NOT NULL COMMENT '作者用户 ID',
    `slug` VARCHAR(128) NOT NULL COMMENT '公开访问标识',
    `summary` VARCHAR(512) NOT NULL DEFAULT '' COMMENT '公开摘要',
    `tags` JSON NULL COMMENT '公开标签数组',
    `access_type` VARCHAR(16) NOT NULL COMMENT '访问类型: FREE/PAID',
    `price_cents` INT NOT NULL DEFAULT 0 COMMENT '单次永久解锁价格，单位分',
    `publication_status` VARCHAR(16) NOT NULL DEFAULT 'UNPUBLISHED' COMMENT '作者发布状态: PUBLISHED/UNPUBLISHED',
    `moderation_status` VARCHAR(16) NOT NULL DEFAULT 'APPROVED' COMMENT '平台审核状态: APPROVED/SUSPENDED',
    `moderated_by` BIGINT NULL COMMENT '最后审核管理员 ID',
    `moderated_at` DATETIME NULL COMMENT '最后审核时间',
    `moderation_reason` VARCHAR(255) NULL COMMENT '审核或暂停原因',
    `current_revision_id` BIGINT NULL COMMENT '当前公开快照版本 ID',
    `public_consent_at` DATETIME NULL COMMENT '作者确认公开隐私风险的时间',
    `published_at` DATETIME NULL COMMENT '首次发布时间',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观版本号',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_market_listing_resume` (`resume_id`),
    UNIQUE KEY `uk_market_listing_slug` (`slug`),
    KEY `idx_market_listing_seller` (`seller_user_id`, `updated_at`),
    KEY `idx_market_listing_public` (`publication_status`, `moderation_status`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户公开简历市场条目';

CREATE TABLE IF NOT EXISTS `resume_market_listing_revision` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `listing_id` BIGINT NOT NULL COMMENT '市场条目 ID',
    `revision_no` INT NOT NULL COMMENT '条目内递增版本号',
    `title_snapshot` VARCHAR(128) NOT NULL COMMENT '简历标题快照',
    `template_id_snapshot` VARCHAR(64) NOT NULL DEFAULT 'default' COMMENT '模板快照',
    `summary_snapshot` VARCHAR(512) NOT NULL DEFAULT '' COMMENT '公开摘要快照',
    `tags_snapshot` JSON NULL COMMENT '公开标签快照',
    `access_type_snapshot` VARCHAR(16) NOT NULL COMMENT '访问类型快照: FREE/PAID',
    `price_cents_snapshot` INT NOT NULL DEFAULT 0 COMMENT '价格快照，单位分',
    `modules_snapshot` JSON NOT NULL COMMENT '去除内部 ID 后的简历模块快照',
    `source_resume_updated_at` DATETIME NULL COMMENT '生成快照时源简历更新时间',
    `content_hash` CHAR(64) NOT NULL COMMENT '快照内容 SHA-256',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_market_revision_no` (`listing_id`, `revision_no`),
    KEY `idx_market_revision_listing` (`listing_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户公开简历不可变版本';

CREATE TABLE IF NOT EXISTS `resume_view_order` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `order_no` VARCHAR(64) NOT NULL COMMENT '平台订单号',
    `buyer_user_id` BIGINT NOT NULL COMMENT '购买用户 ID',
    `seller_user_id` BIGINT NOT NULL COMMENT '作者用户 ID',
    `listing_id` BIGINT NOT NULL COMMENT '市场条目 ID',
    `listing_revision_id` BIGINT NOT NULL COMMENT '购买时条目版本 ID',
    `idempotency_key` VARCHAR(64) NOT NULL COMMENT '客户端幂等键',
    `active_order_key` VARCHAR(96) NULL COMMENT '未结束订单唯一键: listingId:buyerId',
    `amount_cents` INT NOT NULL COMMENT '实付金额，单位分',
    `platform_fee_cents` INT NOT NULL DEFAULT 0 COMMENT '平台服务费，单位分',
    `seller_income_cents` INT NOT NULL COMMENT '作者收入，单位分',
    `currency` VARCHAR(8) NOT NULL DEFAULT 'CNY' COMMENT '币种',
    `provider` VARCHAR(24) NOT NULL COMMENT '支付提供方',
    `pay_channel` VARCHAR(24) NOT NULL COMMENT '支付渠道',
    `order_status` VARCHAR(24) NOT NULL DEFAULT 'CREATED' COMMENT '订单状态',
    `provider_prepay_id` VARCHAR(128) NULL COMMENT '支付平台预支付标识',
    `code_url` TEXT NULL COMMENT 'Native 支付二维码内容',
    `provider_transaction_id` VARCHAR(128) NULL COMMENT '支付平台交易号',
    `expires_at` DATETIME NOT NULL COMMENT '订单过期时间',
    `last_checked_at` DATETIME NULL COMMENT '最近一次主动向支付平台查单时间',
    `paid_at` DATETIME NULL COMMENT '支付完成时间',
    `closed_at` DATETIME NULL COMMENT '订单关闭时间',
    `refunded_at` DATETIME NULL COMMENT '退款完成时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_resume_view_order_no` (`order_no`),
    UNIQUE KEY `uk_resume_view_order_idempotency` (`buyer_user_id`, `idempotency_key`),
    UNIQUE KEY `uk_resume_view_order_active` (`active_order_key`),
    UNIQUE KEY `uk_resume_view_order_transaction` (`provider`, `provider_transaction_id`),
    KEY `idx_resume_view_order_buyer` (`buyer_user_id`, `created_at`),
    KEY `idx_resume_view_order_seller` (`seller_user_id`, `created_at`),
    KEY `idx_resume_view_order_listing` (`listing_id`, `order_status`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='付费简历查看订单';

CREATE TABLE IF NOT EXISTS `resume_view_entitlement` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `listing_id` BIGINT NOT NULL COMMENT '市场条目 ID',
    `listing_revision_id` BIGINT NOT NULL COMMENT '购买时解锁版本 ID',
    `buyer_user_id` BIGINT NOT NULL COMMENT '购买用户 ID',
    `source_order_id` BIGINT NOT NULL COMMENT '来源订单 ID',
    `entitlement_status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '权益状态: ACTIVE/REVOKED',
    `granted_at` DATETIME NOT NULL COMMENT '授权时间',
    `revoked_at` DATETIME NULL COMMENT '撤销时间',
    `revoke_reason` VARCHAR(255) NULL COMMENT '撤销原因',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_resume_entitlement_buyer` (`listing_id`, `buyer_user_id`),
    UNIQUE KEY `uk_resume_entitlement_order` (`source_order_id`),
    KEY `idx_resume_entitlement_buyer` (`buyer_user_id`, `granted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='付费简历永久查看权益';

CREATE TABLE IF NOT EXISTS `creator_wallet` (
    `user_id` BIGINT NOT NULL COMMENT '作者用户 ID',
    `pending_balance_cents` BIGINT NOT NULL DEFAULT 0 COMMENT '待结算余额，单位分',
    `available_balance_cents` BIGINT NOT NULL DEFAULT 0 COMMENT '可结算余额，单位分',
    `lifetime_earned_cents` BIGINT NOT NULL DEFAULT 0 COMMENT '累计收入，单位分',
    `paid_out_cents` BIGINT NOT NULL DEFAULT 0 COMMENT '累计已结算金额，单位分',
    `version` INT NOT NULL DEFAULT 0 COMMENT '乐观版本号',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='简历作者站内收益账户';

CREATE TABLE IF NOT EXISTS `creator_earning` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `seller_user_id` BIGINT NOT NULL COMMENT '作者用户 ID',
    `listing_id` BIGINT NOT NULL COMMENT '市场条目 ID',
    `order_id` BIGINT NOT NULL COMMENT '来源订单 ID',
    `gross_amount_cents` INT NOT NULL COMMENT '订单原始金额，单位分',
    `platform_fee_cents` INT NOT NULL DEFAULT 0 COMMENT '平台服务费，单位分',
    `net_amount_cents` INT NOT NULL COMMENT '作者净收入，单位分',
    `earning_status` VARCHAR(24) NOT NULL DEFAULT 'AVAILABLE' COMMENT '收益状态: AVAILABLE/PENDING_SETTLEMENT/SETTLED/REVERSED',
    `available_at` DATETIME NULL COMMENT '可结算时间',
    `reversed_at` DATETIME NULL COMMENT '退款冲销时间',
    `settled_by` BIGINT NULL COMMENT '线下结算管理员 ID',
    `settled_at` DATETIME NULL COMMENT '线下结算时间',
    `settlement_note` VARCHAR(255) NULL COMMENT '线下转账流水或备注',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_creator_earning_order` (`order_id`),
    KEY `idx_creator_earning_seller` (`seller_user_id`, `earning_status`, `created_at`),
    KEY `idx_creator_earning_listing` (`listing_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='简历作者收益明细';
