#!/usr/bin/env bash
set -euo pipefail
set +x
umask 077

readonly mysql_database="pai_resume"
readonly mysql_username="pai_resume"
readonly mysql_account_host="localhost"
readonly mysql_client_host="127.0.0.1"
readonly mysql_socket="/var/lib/mysql/mysql.sock"
readonly mysql_ca="/var/lib/mysql/ca.pem"
readonly credential_file="/etc/pai-resume/mysql-app.env"

fail() {
  printf '%s\n' "$1" >&2
  exit 1
}

[[ "$(id -u)" == "0" ]] || fail "必须以 root 身份创建 PaiResume MySQL 账号"
[[ -S "$mysql_socket" ]] || fail "MySQL Unix socket 不存在：${mysql_socket}"
[[ -r "$mysql_ca" && ! -L "$mysql_ca" ]] || fail "MySQL CA 不存在或不可安全读取：${mysql_ca}"
[[ -d "$(dirname "$credential_file")" \
  && ! -L "$(dirname "$credential_file")" ]] \
  || fail "PaiResume 配置目录不存在或是符号链接"

mysql_root=(
  mysql
  --protocol=socket
  "--socket=${mysql_socket}"
  --user=root
  --batch
  --skip-column-names
)

active_client_config=""
temporary_credential=""
created_account=false
cleanup() {
  if [[ -n "$active_client_config" ]]; then
    rm -f -- "$active_client_config"
  fi
  if [[ -n "$temporary_credential" ]]; then
    rm -f -- "$temporary_credential"
  fi
  if [[ "$created_account" == "true" ]]; then
    printf "DROP USER IF EXISTS '%s'@'%s';\n" \
      "$mysql_username" "$mysql_account_host" | "${mysql_root[@]}" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT
trap 'exit 1' HUP INT TERM

database_exists="$("${mysql_root[@]}" --execute \
  "SELECT COUNT(*) FROM information_schema.schemata WHERE schema_name='${mysql_database}'")"
[[ "$database_exists" == "1" ]] || fail "数据库 ${mysql_database} 不存在"

read_credential() {
  local wanted_key="$1"
  local line=""
  local key=""
  local value=""
  local found=false

  CREDENTIAL_VALUE=""
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ -z "$line" || "${line:0:1}" == "#" ]] && continue
    [[ "$line" == *=* ]] || fail "凭据文件格式不合法"
    key="${line%%=*}"
    value="${line#*=}"
    [[ "$key" =~ ^[A-Z_]+$ && "$value" != *$'\r'* \
      && "$value" != *$'\n'* ]] || fail "凭据文件包含不安全内容"
    if [[ "$key" == "$wanted_key" ]]; then
      [[ "$found" == "false" ]] || fail "凭据文件重复定义 ${wanted_key}"
      CREDENTIAL_VALUE="$value"
      found=true
    fi
  done < "$credential_file"
  [[ "$found" == "true" ]] || fail "凭据文件缺少 ${wanted_key}"
}

verify_application_login() {
  local password="$1"
  local result=""

  active_client_config="$(mktemp /etc/pai-resume/.mysql-client.tmp.XXXXXX)"
  chmod 0600 "$active_client_config"
  {
    printf '[client]\n'
    printf 'user=%s\n' "$mysql_username"
    printf 'password=%s\n' "$password"
    printf 'host=%s\n' "$mysql_client_host"
    printf 'protocol=tcp\n'
    printf 'ssl-mode=VERIFY_CA\n'
    printf 'ssl-ca=%s\n' "$mysql_ca"
  } > "$active_client_config"

  if ! result="$(mysql --defaults-extra-file="$active_client_config" \
    --database="$mysql_database" --batch --skip-column-names \
    --execute "SELECT 1")"; then
    rm -f -- "$active_client_config"
    active_client_config=""
    fail "PaiResume MySQL 账号连接校验失败"
  fi
  rm -f -- "$active_client_config"
  active_client_config=""
  [[ "$result" == "1" ]] || fail "PaiResume MySQL 账号连接校验失败"
}

if [[ -e "$credential_file" ]]; then
  [[ -f "$credential_file" && ! -L "$credential_file" ]] \
    || fail "现有 MySQL 凭据文件不是普通文件或是符号链接"
  credential_mode="$(stat -c '%a' "$credential_file")"
  [[ "$credential_mode" == "600" ]] || fail "MySQL 凭据文件权限必须为 600"
  read_credential MYSQL_USERNAME
  stored_username="$CREDENTIAL_VALUE"
  read_credential MYSQL_PASSWORD
  stored_password="$CREDENTIAL_VALUE"
  [[ "$stored_username" == "$mysql_username" ]] || fail "MySQL 凭据文件用户名不匹配"
  [[ "$stored_password" =~ ^[A-Za-z0-9!@#%+=._-]{32,96}$ ]] \
    || fail "MySQL 凭据密码格式不符合预期"

  account_exists="$("${mysql_root[@]}" --execute \
    "SELECT COUNT(*) FROM mysql.user WHERE User='${mysql_username}' AND Host='${mysql_account_host}'")"
  [[ "$account_exists" == "1" ]] || fail "凭据文件存在，但 MySQL 账号不存在"
  verify_application_login "$stored_password"
  trap - EXIT HUP INT TERM
  printf 'PaiResume MySQL 账号已存在并通过本机 TLS 校验；未输出或轮换密码。\n'
  exit 0
fi

account_exists="$("${mysql_root[@]}" --execute \
  "SELECT COUNT(*) FROM mysql.user WHERE User='${mysql_username}' AND Host='${mysql_account_host}'")"
[[ "$account_exists" == "0" ]] \
  || fail "MySQL 账号已存在但缺少本地凭据文件，拒绝接管或重置密码"

command -v openssl >/dev/null 2>&1 || fail "缺少 openssl，无法生成强密码"
generated_password="A9!$(openssl rand -hex 28)z@"
[[ "$generated_password" =~ ^[A-Za-z0-9!@#%+=._-]{32,96}$ ]] \
  || fail "未生成预期格式的 MySQL 密码"

temporary_credential="$(mktemp /etc/pai-resume/.mysql-app.env.tmp.XXXXXX)"
chmod 0600 "$temporary_credential"

{
  printf '# Generated by scripts/bootstrap-mysql-account.sh; do not edit manually.\n'
  printf 'MYSQL_USERNAME=%s\n' "$mysql_username"
  printf 'MYSQL_PASSWORD=%s\n' "$generated_password"
} > "$temporary_credential"

printf "CREATE USER '%s'@'%s' IDENTIFIED WITH caching_sha2_password BY '%s' REQUIRE SSL WITH MAX_USER_CONNECTIONS 12;\n" \
  "$mysql_username" "$mysql_account_host" "$generated_password" | "${mysql_root[@]}"
created_account=true
printf 'GRANT ALL PRIVILEGES ON `%s`.* TO '\''%s'\''@'\''%s'\'';\n' \
  "$mysql_database" "$mysql_username" "$mysql_account_host" | "${mysql_root[@]}"

verify_application_login "$generated_password"
schema_privilege_count="$("${mysql_root[@]}" --execute \
  "SELECT COUNT(*) FROM information_schema.schema_privileges
   WHERE grantee=CONCAT(CHAR(39),'${mysql_username}',CHAR(39),'@',CHAR(39),'${mysql_account_host}',CHAR(39))
     AND table_schema='${mysql_database}'")"
tls_resource_count="$("${mysql_root[@]}" --execute \
  "SELECT COUNT(*) FROM mysql.user
   WHERE User='${mysql_username}' AND Host='${mysql_account_host}'
     AND ssl_type='ANY' AND max_user_connections=12")"
[[ "$schema_privilege_count" =~ ^[0-9]+$ \
  && "$schema_privilege_count" -ge 10 \
  && "$tls_resource_count" == "1" ]] \
  || fail "MySQL 账号授权或 TLS 要求校验失败"

chown root:root "$temporary_credential"
mv -- "$temporary_credential" "$credential_file"
temporary_credential=""
created_account=false
trap - EXIT HUP INT TERM

printf '已创建一个 PaiResume MySQL 账号，仅供应用与 Flyway 共用；凭据保存在权限 600 的服务器文件中。\n'
